In [20]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.layers import Dense
from sklearn.metrics import confusion_matrix, classification_report
from keras.models import Sequential

In [21]:
data = np.genfromtxt("../DATA/bank_note_data.txt",delimiter = ',')

In [22]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [23]:
data[:,4]

array([0., 0., 0., ..., 1., 1., 1.])

In [24]:
data[:,:4]

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [25]:
X = data[:,:4]
y = data[:,4]

In [26]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42)

In [9]:
scaler = MinMaxScaler()

In [27]:
X_trainsc = scaler.fit_transform(X_train)

In [28]:
X_testsc = scaler.transform(X_test)

In [29]:
model = Sequential()

In [30]:
model.add(Dense(4,activation='relu',input_dim=4))

In [31]:
model.add(Dense(8,activation='relu'))

In [32]:
model.add(Dense(1,activation='sigmoid'))

In [34]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
model.fit(x=X_trainsc,y=y_train,epochs=50,verbose=2)

Epoch 1/50
 - 3s - loss: 0.7137 - acc: 0.4385
Epoch 2/50
 - 0s - loss: 0.6884 - acc: 0.4875
Epoch 3/50
 - 0s - loss: 0.6717 - acc: 0.5708
Epoch 4/50
 - 0s - loss: 0.6593 - acc: 0.6135
Epoch 5/50
 - 0s - loss: 0.6482 - acc: 0.6521
Epoch 6/50
 - 0s - loss: 0.6374 - acc: 0.6740
Epoch 7/50
 - 0s - loss: 0.6263 - acc: 0.6802
Epoch 8/50
 - 0s - loss: 0.6142 - acc: 0.6917
Epoch 9/50
 - 0s - loss: 0.6014 - acc: 0.7021
Epoch 10/50
 - 0s - loss: 0.5873 - acc: 0.7094
Epoch 11/50
 - 0s - loss: 0.5718 - acc: 0.7094
Epoch 12/50
 - 0s - loss: 0.5559 - acc: 0.7198
Epoch 13/50
 - 0s - loss: 0.5405 - acc: 0.7281
Epoch 14/50
 - 0s - loss: 0.5253 - acc: 0.7437
Epoch 15/50
 - 0s - loss: 0.5114 - acc: 0.7677
Epoch 16/50
 - 0s - loss: 0.4974 - acc: 0.7740
Epoch 17/50
 - 0s - loss: 0.4834 - acc: 0.7802
Epoch 18/50
 - 0s - loss: 0.4707 - acc: 0.7927
Epoch 19/50
 - 0s - loss: 0.4575 - acc: 0.7979
Epoch 20/50
 - 0s - loss: 0.4448 - acc: 0.8135
Epoch 21/50
 - 0s - loss: 0.4321 - acc: 0.8208
Epoch 22/50
 - 0s - lo

In [37]:
pred = model.predict_classes(X_test)

In [38]:
print(confusion_matrix(y_test,pred))

[[190  39]
 [  3 180]]


In [39]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

        0.0       0.98      0.83      0.90       229
        1.0       0.82      0.98      0.90       183

avg / total       0.91      0.90      0.90       412

